#
# PX4 ROS 2 Humble development environment
# Based from container under https://github.com/osrf/docker_images/tree/master/ros2/source/devel
#

ARG BASE=px4io/px4-dev-base-jammy
FROM ${BASE}
LABEL maintainer="Peter Breuer <pbreuer@ethz.ch>"

# Optional build arguments
ARG USER_UID=1000
ARG USER_GID=$USER_UID

# Environment variables (available to container)
ENV ROS_DISTRO=humble
ENV USERNAME dev

# Setup ROS 2 keys
RUN curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key -o /usr/share/keyrings/ros-archive-keyring.gpg

# Setup sources.list
RUN echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] http://packages.ros.org/ros2/ubuntu $(lsb_release -cs) main" | tee /etc/apt/sources.list.d/ros2.list > /dev/null

# Install bootstrap tools
RUN apt-get update \
	&& apt-get install --quiet -y \
		python3-colcon-common-extensions \
		python3-colcon-mixin \
		python3-rosdep \
		python3-vcstool \
		# Text banner (not required)
  		figlet \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	# Clean the apt package index to reduce the image size
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# Install ROS 2 desktop
RUN apt-get install --quiet --no-install-recommends -y \
		ros-$ROS_DISTRO-desktop \
		ros-$ROS_DISTRO-launch-testing-ament-cmake \
		ros-$ROS_DISTRO-ros2bag \
		ros-$ROS_DISTRO-rosidl-generator-dds-idl \
	&& apt-get -y autoremove \
	&& apt-get clean autoclean \
	&& rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

# Install Python 3 packages needed for testing
RUN pip3 install -U \
		argcomplete \
		flake8 \
		flake8-blind-except \
		flake8-builtins \
		flake8-class-newline \
		flake8-comprehensions \
		flake8-deprecated \
		flake8-docstrings \
		flake8-import-order \
		flake8-quotes \
		pytest-repeat \
		pytest-rerunfailures

# Bootstrap rosdep
RUN rosdep init && rosdep update

# Setup colcon mixin and metadata
RUN colcon mixin add default \
		https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml \
	&& colcon mixin update \
	&& colcon metadata add default \
		https://raw.githubusercontent.com/colcon/colcon-metadata-repository/master/index.yaml \
	&& colcon metadata update

# Install Micro-XRCE-DDS-Agent
RUN git clone https://github.com/eProsima/Micro-XRCE-DDS-Agent.git /tmp/micro-xrce-dds-agent \
    && cd /tmp/micro-xrce-dds-agent \
	&& mkdir build && cd build \
	&& cmake .. \
	&& make -j $(nproc) && make install \
	&& ldconfig /usr/local/lib \
	&& rm -rf /tmp/*

# Non-root user
RUN groupadd --gid $USER_GID $USERNAME \
  && useradd --uid $USER_UID --gid $USER_GID -s /bin/bash -m $USERNAME \
  && apt install -y sudo \
  # Add sudo support (without password) for the non-root user
  && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
  # Ensure new file is in correct mode
  && chmod 0440 /etc/sudoers.d/$USERNAME \
  && rm -rf /var/lib/apt/lists/*

# Create and start as LOCAL_USER_ID
COPY scripts/entrypoint.sh /usr/local/bin/
# COPY rosdep.sh /usr/local/bin/ # TODO: add this once we need it
# RUN chmod +x /usr/local/bin/rosdep.sh
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["/bin/bash"]
